
logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog-dev.log

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calligraphy?&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 1634074538@qq.com
    password: fulrlobtsucicdfe
    from: 1634074538@qq.com
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    default-encoding: utf-8
    protocol: smtp
    port: 587
    properties.mail.stmp.auth: true



mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/**.xml
entity_package: com.music.bcmusic.domain
    
mapper:
    mappers: tk.mybatis.mapper.common.Mapper
    notEmpty: true


#mybatis
#mybatis_config_file=mybatis-config.xml
#mapper_path=/mapper/**.xml
#entity_package=com.music.bcmusic.domain

# mybatis mapper helper
#mapper.mappers=tk.mybatis.mapper.common.Mapper
#mapper.notEmpty=true


